apiVersion: apps/v1
kind: Deployment
env:
  - name: SKIP_DB_SYNC
    value: "true"
metadata:
  name: donimoney
  labels:
    app: donimoney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donimoney
  template:
    metadata:
      labels:
        app: donimoney
    spec:
      containers:
        - name: app
          image: docker.io/jinseon901/test:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

